### PR TITLE
Use automergeType pr on renovate rector update next version

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

To make new PR on next rector release with pinned version.

### CODE REVIEW

**Comment by samsonasik** [comment]
@Ocramius @internalsystemerror All green 🎉 it is ready for review.

**Comment by Ocramius** [comment]
Do you really prefer PRs for this? The whole point of renovate was that it's a bit more silent than @dependabot 😅

**Comment by samsonasik** [comment]
that's to make user got latest bug fix on rector, I don't know if any other solution better than it. It only create PR for rector, not other dependency, eg: phpstan update https://github.com/laminas/laminas-servicemanager-migration/commit/f4ec894432d71a015255a8150bbe67758655d59a

**Comment by internalsystemerror** [comment]
> that's to make user got latest bug fix on rector, I don't know if any other solution better than it. It only create PR for rector, not other dependency, eg: phpstan update [f4ec894](https://github.com/laminas/laminas-servicemanager-migration/commit/f4ec894432d71a015255a8150bbe67758655d59a)

With this change, when rector `0.12.21` is released, a new PR will be opened and automerged (if passing) to update `composer.json` and `composer.lock` to set `"rector/rector": "0.12.21"`.

> Do you really prefer PRs for this? The whole point of renovate was that it's a bit more silent than @dependabot 😅

I believe this is purely so that the automatic release process can be used whilst ensuring that the version of rector is fixed to a single version rather than a range. Does that process require any labels to be set? I'm not that familiar with it. You mentioned in https://github.com/laminas/laminas-servicemanager-migration/pull/65 that the PR needs to be part of a milestone? I'm not sure of a way to assign the PR to a milestone automatically using renovate, so that part may still require manual intervention.

**Comment by samsonasik** [comment]
@internalsystemerror milestone is needed as far as I know, but can be added manually later after PR automatically merged before create new release.

**Comment by Ocramius** [comment]
OK, if this is your preference, let's go ahead and roll with it: just beware that I'll probably un-watch the repository then, as I already am at ~500mails/day

**Comment by samsonasik** [comment]
@Ocramius that's ok, I will ping you if I need your review. Let's make it open some time in case any other opinion coming for it ;)

**Review by Ocramius — APPROVED** [review]

**Comment by samsonasik** [comment]
I am merging it ;)

**Pull request merged**
