### PR TITLE
Using rector/rector:^0.12.20 instead of pinned version

### PR DESCRIPTION
**Pull request by samsonasik**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Hi @internalsystemerror , as if there is error after update, the PR will be created by `renovate`, I am thinking the version should be ok with `rector/rector:^0.12.20`, what do you think? is the configuration update for renovate.json correct? 

Thank you.

### CODE REVIEW

**Comment by Ocramius** [comment]
@samsonasik depends on whether we use things `@internal` to rector, or just its publicly declared API

**Comment by internalsystemerror** [comment]
This is essentially reverting https://github.com/laminas/laminas-servicemanager-migration/pull/62 to allow for a version range instead of a fixed version? The default configuration from laminas should be attempting to update the lockfile on new version releases, opening a PR if that fails. So after merging of this PR, once `0.12.21` is released, a lockfile update will be attempted (with a PR opened if there is an error) and the compose.json constraint will stay as `^0.12.20`. Is this the desired outcome?

**Comment by samsonasik** [comment]
@Ocramius mostly usage are public API used here as far as I know, but if they are changed/removed, that's can be updated early as error test will cause new PR from renovate.

@internalsystemerror yes, it is, as if there is no bug fix/feature coming, then the composer.lock and composer.json only updated in `0.4.x-dev` without any new tag, while user need to use : 

```
composer update laminas/laminas-servicemanager-migration:0.4.x-dev
```

the another solution is update documentation to use latest `-dev` version to get latest rector version.

**Comment by Ocramius** [comment]
>  if they are changed/removed, that's can be updated early as error test will cause new PR from renovate.

Remember that people installing `laminas/laminas-servicemanager-migration` will get whatever the range allows ;-) It drills down to whether rector is SemVer compliant.

**Comment by samsonasik** [comment]
@Ocramius ok, I am closing it then ;) @Ocramius @internalsystemerror thank you for the review.

**Comment by internalsystemerror** [comment]
Just to be clear. As it currently stands with the version pinned to `0.12.20`, once `0.12.21` comes out, then renovate will attempt to update both `composer.json` and `composer.lock` to have version `0.12.21` set. In order for users to then use this new version of renovate, a release will need to be made of this package.

> Remember that people installing laminas/laminas-servicemanager-migration will get whatever the range allows ;-) It drills down to whether rector is SemVer compliant.

The only allowed range at the moment will be the exact version of rector specified in `composer.json` of this package.

**Comment by samsonasik** [comment]
@Ocramius is there a way to make automatic release when the composer.lock and composer.json updated from renovate, eg on next pinned rector 0.12.21?

**Comment by Ocramius** [comment]
No, the automatic release process expects pull requests/issues to be part of a milestone, and AFAIK refuses empty changelog (which is most likely a bug or mistake by release manager).

**Comment by internalsystemerror** [comment]
You could tell renovate to open a PR for any update of rector?

```json
"packageRules": [
    {"matchPackageNames": ["rector/rector"], "automergeType": "pr"}
]
```

See [`automergeType`](https://docs.renovatebot.com/configuration-options/#automergetype)

**Comment by samsonasik** [comment]
@internalsystemerror Thank you, I create PR https://github.com/laminas/laminas-servicemanager-migration/pull/66 for it.

**Pull request closed without merging**
